version: '3.8'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suxx
    volumes:
      - "./database.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "33306:3306"
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8083:80"
    volumes:
      - "./html/:/var/www/html/"
    depends_on:
      - mysql
